version: 2.1

executors:
  go-container:
    docker:
      - image: circleci/golang:1.15
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://proxy.golang.org"

jobs:
  # Run static Go-related checks, e.g. code formatting.
  go-checks:
    executor: go-container
    steps:
      - checkout
      - run:
          name: Install goimports tool
          command: |
            go get -u golang.org/x/tools/cmd/goimports
            echo "export PATH=$GOPATH/bin:$PATH" >> $BASH_ENV
      - run:
          name: Check Go format
          command: "! go fmt ./... | read"
      - run:
          name: Check Go imports
          command: "! goimports ./... | read"

  # Run all Go tests.
  go-test:
    executor: go-container
    steps:
      - checkout
      - restore_cache:
          keys:
            - gomodules-v1-{{ checksum "go.mod" }}
            - gomodules-v1-
      - run:
          name: Download dependencies
          command: go mod download
      - save_cache:
          key: gomodules-v1-{{ checksum "go.mod" }}
          paths: /go/pkg
      - run:
          name: Run all tests
          command: go test -v ./...

  # Verify that the requirements for creating a new release are met.
  pre-release-check:
    executor: go-container
    steps:
      - checkout
      - run:
          name: Check release in CHANGELOG.md
          command: python jobs.py --run check-changelog --tag=${CIRCLE_TAG}

  # Build buneary binaries for multiple platforms.
  build:
    executor: go-container
    steps:
      - checkout
      - restore_cache:
          keys:
            - gomodules-v1-{{ checksum "go.mod" }}
            - gomodules-v1-
      - run:
          name: Download dependencies
          command: go mod download
      - save_cache:
          key: gomodules-v1-{{ checksum "go.mod" }}
          paths: /go/pkg
      - run: mkdir -p /tmp/artifacts
      - run:
          name: Build and pack buneary for Linux
          command: |
            GOOS=linux GOARCH=amd64 go build -v -ldflags "-X main.version=${CIRCLE_TAG}" \
              -o target/buneary cmd/main.go
            cp target/buneary buneary
            tar -czf /tmp/artifacts/buneary-linux-amd64.tar.gz buneary
            rm buneary
      - run:
          name: Build and pack buneary for macOS
          command: |
            GOOS=darwin GOARCH=amd64 go build -v -ldflags "-X main.version=${CIRCLE_TAG}" \
              -o target/buneary cmd/main.go
            cp target/buneary buneary
            tar -czf /tmp/artifacts/buneary-macos-amd64.tar.gz buneary
            rm buneary
      - run:
          name: Build and pack buneary for Windows
          command: |
            GOOS=windows GOARCH=amd64 go build -v -ldflags "-X main.version=${CIRCLE_TAG}" \
              -o target/buneary.exe cmd/main.go
            cp target/buneary.exe buneary.exe
            zip /tmp/artifacts/buneary-windows-amd64.zip buneary.exe
            rm buneary.exe
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - buneary-*

  # Release the packaged binaries to GitHub.
  release-github:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: Install Python
          command: apk add --no-cache python2
      #- run:
      #    name: Get the release changelog
      #    command: echo "export CHANGELOG=$(python ./scripts/print_changelog.py)" >> $BASH_ENV
      - run:
          name: Publish GitHub release
          command: |
            ghr -t "${GITHUB_TOKEN}" \
                -u "${CIRCLE_PROJECT_USERNAME}" \
                -r "${CIRCLE_PROJECT_REPONAME}" \
                -c "${CIRCLE_SHA1}" \
                -b "$(python jobs.py --run=print-changelog --tag=${CIRCLE_TAG})" \
                -delete "${CIRCLE_TAG}" \
                /tmp/artifacts

  # Release the Docker images to Docker Hub and GitHub Packages.
  release-docker:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Log in to Docker Hub
          command: |
            echo ${DOCKER_PASS} | docker login --username ${DOCKER_USER} --password-stdin
      - run:
          name: Build the distribution Docker image
          command: |
            docker image build --build-arg VERSION=${CIRCLE_TAG} -t dominikbraun/buneary:${CIRCLE_TAG} -f Dockerfile .
      - run:
          name: Tag the Docker images as latest
          command: |
            docker image tag dominikbraun/buneary:${CIRCLE_TAG} dominikbraun/buneary:latest
      - run:
          name: Publish the image on Docker Hub
          command: |
            docker image push dominikbraun/buneary:${CIRCLE_TAG}
            docker image push dominikbraun/buneary:latest
      - run:
          name: Log in to GitHub Packages
          command: |
            docker logout
            echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com --username ${GITHUB_USER} --password-stdin
      - run:
          name: Tag the previously built Docker image
          command: |
            docker image tag dominikbraun/buneary:${CIRCLE_TAG} docker.pkg.github.com/dominikbraun/buneary/buneary:${CIRCLE_TAG}
      - run:
          name: Publish the image on GitHub Packages
          command: |
            docker image push docker.pkg.github.com/dominikbraun/buneary/buneary:${CIRCLE_TAG}

workflows:
  version: 2
  # The basic CI workflow for single commits and opened PRs.
  buneary-ci:
    jobs:
      - go-checks
      - go-test:
          requires:
            - go-checks
  # The workflow for delivering the buneary application.
  buneary-cd:
    jobs:
      - pre-release-check:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - pre-release-check
          filters:
            tags:
              only: /v.*/
      - release-github:
          requires:
            - build
          filters:
            tags:
              only: /v.*/
      - release-docker:
          requires:
            - release-github
          filters:
            tags:
              only: /v.*/